apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-serv
    app: demo-voting-app-ira

spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-pod-ira
    app: demo-voting-app-ira




