apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod-ira
  labels:
    name: voting-app-pod-ira
    app: demo-voting-app-ira

spec:
  containers:
    - name: voting-app-ira
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80


